version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - jarvis-core
    allow:
      - dependency-name: jarvis-agent-core

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
